/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#ifndef _COM_P2PAPI_JNI_
#define _COM_P2PAPI_JNI_
#ifdef __cplusplus
extern "C" 
{
#endif

JNIEXPORT void JNICALL Java_com_p2papi_jni_NativeCaller_Init(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_p2papi_jni_NativeCaller_Free(JNIEnv *, jobject);

JNIEXPORT int JNICALL Java_com_p2papi_jni_NativeCaller_StartP2P(JNIEnv *, jobject);

JNIEXPORT int JNICALL Java_com_p2papi_jni_NativeCaller_StopP2P(JNIEnv *, jobject);

JNIEXPORT int JNICALL Java_com_p2papi_jni_NativeCaller_StartVideo(JNIEnv *, jobject);

JNIEXPORT int JNICALL Java_com_p2papi_jni_NativeCaller_StopVideo(JNIEnv *, jobject);

JNIEXPORT int JNICALL Java_com_p2papi_jni_NativeCaller_StartAudio(JNIEnv *, jobject);

JNIEXPORT int JNICALL Java_com_p2papi_jni_NativeCaller_StopAudio(JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif

#endif


